### ISSUE TITLE
debian package build in sonic-slave build env fails

### ISSUE THREAD

**Issue by lguohan** [aristanetworks/sonic#1]
johnar@2bd1283802d3:/mnt/sonic/sonic$ dpkg-buildpackage -us -uc -b           
dpkg-buildpackage: source package sonic-platform-arista
dpkg-buildpackage: source version 1.0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Samuel Angebault <staphylo@arista.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build sonic
dpkg-source: warning: can't parse dependency ${python:Depends}
dpkg-source: error: error occurred while parsing Build-Depends
dpkg-buildpackage: error: dpkg-source --before-build sonic gave error exit status 255

**Comment by Staphylo** [comment]
Fixed by #2 with e31aa7d4eeb64dd7abe42c1b78255910a020ecb8
