### ISSUE TITLE
Is 7050sx3-48cy12 supported?

### ISSUE THREAD

**Issue by mnasiadka** [aristanetworks/sonic#100]
I've noticed 7050sx3-48yc8 platform in the code, but is yc12 supported as well?

**Comment by Staphylo** [comment]
This product is not supported and we don't have any plans on bringing SONiC to this platform (`-48YC12`).
Note that even though the `-48YC8` has its platform supported in this repo, the dataplane is not coming up due to some SAI initialization issue, so it's not really usable either.
