### ISSUE TITLE
[chassis T2] link issue

### ISSUE THREAD

**Issue by wenyiz2021** [aristanetworks/sonic#101]
there are 2 links that are down/up.
the following work around worked according to Nathan to disable low power mode:

sudo config interface  tran lpmode Ethernet104 disable

sudo config interface  tran lpmode Ethernet108 disable

but by default the low power mode is enabled.

open this issue to root cause.

**Comment by kenneth-arista** [comment]
@Staphylo @arista-nwolfe

**Comment by kenneth-arista** [comment]
Related to the lower power mode discussion

**Comment by kenneth-arista** [comment]
Related PRs
https://github.com/sonic-net/sonic-buildimage/pull/20886
https://github.com/sonic-net/sonic-platform-daemons/pull/565

**Comment by wenyiz2021** [comment]
@rlhui this is still an issue regarding cable type 100GBASE-CWDM4, they need to be set to low power mode to be up now, as WA

**Comment by wenyiz2021** [comment]
100GBASE-CR4 old cable type is good

**Comment by kenneth-arista** [comment]
Corresponding PRs merged. Closing issue
