### ISSUE TITLE
sfputil show does not work on 7260cx3 platform

### ISSUE THREAD

**Issue by lguohan** [aristanetworks/sonic#12]
admin@sonic:/usr/share/sonic/device/x86_64-arista_7260cx3_64/plugins$ sudo sfputil show
getSfpUtil(): Error - Unsupported platform!

**Comment by Staphylo** [comment]
Support of the updated sfputil plugins for the 7260cx3 platform comes with d965c36da597d972d2af2b15692fa2ce8d63e3fb

**Comment by yxieca** [comment]
I've validated that the change addressed the issue. Thanks 👍
