### ISSUE TITLE
tg3 is not ready till very late in the boot process

### ISSUE THREAD

**Issue by lguohan** [aristanetworks/sonic#13]
Aug 24 16:00:55.823443 str-a7050-acs-1 INFO systemd[1]: Starting LSB: Raise network interfaces....
Aug 24 16:00:55.887145 str-a7050-acs-1 INFO systemd[1]: Starting System Logging Service...
Aug 24 16:00:55.952732 str-a7050-acs-1 INFO kernel: [   22.360265] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
Aug 24 16:00:55.961583 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:55.961451820Z" level=warning msg="Your kernel does not support cgroup memory limit"
Aug 24 16:00:55.962021 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:55.961556475Z" level=warning msg="Your kernel does not support cgroup cfs period"
Aug 24 16:00:55.962357 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:55.961596839Z" level=warning msg="Your kernel does not support cgroup cfs quotas"
Aug 24 16:00:55.964004 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:55.963933370Z" level=warning msg="mountpoint for pids not found"
Aug 24 16:00:55.966436 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:55.966336459Z" level=info msg="Loading containers: start."
Aug 24 16:00:56.005084 str-a7050-acs-1 INFO systemd[1]: Started System Logging Service.
Aug 24 16:00:56.014210 str-a7050-acs-1 INFO docker[518]: .........
Aug 24 16:00:56.014910 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:56.014137613Z" level=info msg="Loading containers: done."
Aug 24 16:00:56.015451 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:56.014207538Z" level=info msg="Daemon has completed initialization"
Aug 24 16:00:56.015980 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:56.014258871Z" level=info msg="Docker daemon" commit=5604cbe graphdriver=aufs version=1.11.1
Aug 24 16:00:56.039194 str-a7050-acs-1 INFO docker[518]: time="2017-08-24T16:00:56.039004918Z" level=info msg="API listen on /var/run/docker.sock"
Aug 24 16:00:56.073015 str-a7050-acs-1 INFO systemd[1]: Started Update rsyslog configuration.
Aug 24 16:00:56.144984 str-a7050-acs-1 INFO systemd[1]: Started Docker Application Container Engine.
Aug 24 16:00:56.760756 str-a7050-acs-1 WARNING kernel: [   23.167242] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:00:57.744735 str-a7050-acs-1 WARNING kernel: [   24.151235] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:00:58.728751 str-a7050-acs-1 WARNING kernel: [   25.135243] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:00:59.712763 str-a7050-acs-1 WARNING kernel: [   26.119244] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:00.696740 str-a7050-acs-1 WARNING kernel: [   27.103236] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:01.680732 str-a7050-acs-1 WARNING kernel: [   28.087234] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:02.664753 str-a7050-acs-1 WARNING kernel: [   29.071238] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:03.648734 str-a7050-acs-1 WARNING kernel: [   30.055233] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:04.632763 str-a7050-acs-1 WARNING kernel: [   31.039243] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:05.616733 str-a7050-acs-1 WARNING kernel: [   32.023232] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:06.600765 str-a7050-acs-1 WARNING kernel: [   33.007244] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:30.992764 str-a7050-acs-1 WARNING kernel: [   57.399225] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:31.064735 str-a7050-acs-1 WARNING kernel: [   57.471221] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:31.632733 str-a7050-acs-1 WARNING kernel: [   58.039219] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:01:31.704731 str-a7050-acs-1 WARNING kernel: [   58.111218] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 1"
Aug 24 16:02:04.800766 str-a7050-acs-1 WARNING kernel: [   91.207214] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.224732 str-a7050-acs-1 WARNING kernel: [   91.631206] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.296731 str-a7050-acs-1 WARNING kernel: [   91.703206] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.368733 str-a7050-acs-1 WARNING kernel: [   91.775205] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.440730 str-a7050-acs-1 WARNING kernel: [   91.847204] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.512731 str-a7050-acs-1 WARNING kernel: [   91.919209] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.584733 str-a7050-acs-1 WARNING kernel: [   91.991203] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:05.960732 str-a7050-acs-1 WARNING kernel: [   92.367205] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:06.784736 str-a7050-acs-1 WARNING kernel: [   93.191205] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:07.768739 str-a7050-acs-1 WARNING kernel: [   94.175203] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:08.752735 str-a7050-acs-1 WARNING kernel: [   95.159203] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:09.736736 str-a7050-acs-1 WARNING kernel: [   96.143201] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:10.720736 str-a7050-acs-1 WARNING kernel: [   97.127201] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:11.704738 str-a7050-acs-1 WARNING kernel: [   98.111201] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:12.688737 str-a7050-acs-1 WARNING kernel: [   99.095203] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:13.672734 str-a7050-acs-1 WARNING kernel: [  100.079200] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:14.656739 str-a7050-acs-1 WARNING kernel: [  101.063200] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:15.640733 str-a7050-acs-1 WARNING kernel: [  102.047198] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:16.624736 str-a7050-acs-1 WARNING kernel: [  103.031199] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:17.608737 str-a7050-acs-1 WARNING kernel: [  104.015198] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:41.984756 str-a7050-acs-1 WARNING kernel: [  128.391193] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:42.056736 str-a7050-acs-1 WARNING kernel: [  128.463190] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:42.624741 str-a7050-acs-1 WARNING kernel: [  129.031186] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:42.696732 str-a7050-acs-1 WARNING kernel: [  129.103190] sonic: smbus access failed address=0x4e on adapter="SCD SMBus master 0 bus 5"
Aug 24 16:02:43.240751 str-a7050-acs-1 DEBUG kernel: [  129.647323] tg3 0000:04:00.0: irq 77 for MSI/MSI-X
Aug 24 16:02:43.240787 str-a7050-acs-1 DEBUG kernel: [  129.647341] tg3 0000:04:00.0: irq 78 for MSI/MSI-X
Aug 24 16:02:43.240792 str-a7050-acs-1 DEBUG kernel: [  129.647357] tg3 0000:04:00.0: irq 79 for MSI/MSI-X
Aug 24 16:02:43.240796 str-a7050-acs-1 DEBUG kernel: [  129.647369] tg3 0000:04:00.0: irq 80 for MSI/MSI-X
Aug 24 16:02:43.240818 str-a7050-acs-1 DEBUG kernel: [  129.647380] tg3 0000:04:00.0: irq 81 for MSI/MSI-X
Aug 24 16:02:43.284786 str-a7050-acs-1 INFO kernel: [  129.691834] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Aug 24 16:02:43.389680 str-a7050-acs-1 INFO systemd[1]: Reloading OpenBSD Secure Shell server.
Aug 24 16:02:43.395760 str-a7050-acs-1 INFO systemd[1]: Reloaded OpenBSD Secure Shell server.
Aug 24 16:02:43.430903 str-a7050-acs-1 INFO networking[626]: Configuring network interfaces...done.
Aug 24 16:02:43.431663 str-a7050-acs-1 INFO systemd[1]: Started LSB: Raise network interfaces..

**Comment by lguohan** [comment]
Aug 24 16:00:55.823443 str-a7050-acs-1 INFO systemd[1]: Starting LSB: Raise network interfaces....
Aug 24 16:02:43.431663 str-a7050-acs-1 INFO systemd[1]: Started LSB: Raise network interfaces..

it takes two minutes to raise eth0. other services all depend on this one.

**Comment by Staphylo** [comment]
Fixed with #16
