### ISSUE TITLE
Add Arista-7060 sensors data in sonic-mgmt test repository

### ISSUE THREAD

**Issue by prsunny** [aristanetworks/sonic#19]
Sensor test is failing since there is no data for Arista-7060CX-32S-C32 in sku-sensors-data.yml. Request to update the same in` sku-sensors-data.yml` (./group_vars/sonic/sku-sensors-data.yml) in sonic-mgmt. repo. 

> ASK [test : Gather sensors] ***************************************************
> Friday 03 November 2017  16:42:43 +0000 (0:00:00.112)       0:01:38.320 ******* 
> fatal: [str-7060cx-acs-10]: FAILED! => {"failed": true, "msg": "ERROR! 'dict object' has no attribute u'Arista-7060CX-32S-C32'"}

**Comment by Staphylo** [comment]
This issue has been resolved via a commit on Azure/sonic-mgmt
