### ISSUE TITLE
[Wolverine LC] wrong thermal numbers returned from chassis api

### ISSUE THREAD

**Issue by wenyiz2021** [aristanetworks/sonic#68]
[platform_tests/api/test_chassis.py:403: Failed]
```
try:
num_thermals = int(chassis.get_num_thermals(platform_api_conn))
except:
pytest.fail("num_thermals is not an integer")
else:
if num_thermals == 0:
pytest.skip("No thermals found on device")
if duthost.facts.get("chassis"):
expected_num_thermals = len(duthost.facts.get("chassis").get('thermals'))
pytest_assert(num_thermals == expected_num_thermals,
"Number of thermals ({}) does not match expected number ({})"
>                         .format(num_thermals, expected_num_thermals))
E           Failed: Number of thermals (2) does not match expected number (6)
```

**Comment by wenyiz2021** [comment]
@Staphylo I believe platform.json is correct as you specified for each of the 6 thermals

**Comment by Staphylo** [comment]
I believe the correct number is 2 on Wolverine. The platform.json needs to be updated.
@patrickmacarthur

**Comment by wenyiz2021** [comment]
@Staphylo @patrickmacarthur can you please remove the 4 thermal entries in platform.json? 
or let me know what need to be removed, I can create one

**Comment by patrickmacarthur** [comment]
I have a patch for this that I will submit upstream today.

**Comment by patrickmacarthur** [comment]
PR opened: https://github.com/sonic-net/sonic-buildimage/pull/13524
