### ISSUE TITLE
sfputil -p Ethernet0 get the wrong eeprom data

### ISSUE THREAD

**Issue by lguohan** [aristanetworks/sonic#8]
sfputil -p Ehternet0 should be mapped the /sys/class/i2c-adapter/i2c-9/9-0050/eeprom

currently the sfputil -p Ethernet0 read the eeprom at i2c-11/11-0050/eeprom

this is on 7260cx-3 platform.

**Comment by yxieca** [comment]
This issue has been addressed with the latest sfputil change. 👍
